# Generated by Django 4.2.7 on 2025-11-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IncomeInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="شماره فاکتور"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="مبلغ"
                    ),
                ),
                (
                    "babet",
                    models.CharField(
                        help_text="موضوع یا دلیل درآمد",
                        max_length=255,
                        verbose_name="بابت",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="finance/income_invoices/",
                        verbose_name="فایل پیوست",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور درآمد",
                "verbose_name_plural": "فاکتورهای درآمد",
                "ordering": ["-date", "-invoice_number"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="finance_inc_invoice_39e3b3_idx"
                    ),
                    models.Index(fields=["date"], name="finance_inc_date_d5eb2a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExpenseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="شماره فاکتور"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="مبلغ"
                    ),
                ),
                (
                    "babet",
                    models.CharField(
                        help_text="موضوع یا دلیل هزینه",
                        max_length=255,
                        verbose_name="بابت",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="finance/expense_invoices/",
                        verbose_name="فایل پیوست",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور هزینه",
                "verbose_name_plural": "فاکتورهای هزینه",
                "ordering": ["-date", "-invoice_number"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="finance_exp_invoice_c73f85_idx"
                    ),
                    models.Index(fields=["date"], name="finance_exp_date_437aea_idx"),
                ],
            },
        ),
    ]
