# Generated by Django 4.2.7 on 2025-11-23 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="مبلغ حقوق"
                    ),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="پرداختی")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="salaries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارمند",
                    ),
                ),
            ],
            options={
                "verbose_name": "حقوق",
                "verbose_name_plural": "حقوق\u200cها",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["employee", "date"],
                        name="finance_sal_employe_d7f968_idx",
                    ),
                    models.Index(
                        fields=["is_paid"], name="finance_sal_is_paid_c0fa4a_idx"
                    ),
                ],
            },
        ),
    ]
