# Generated by Django 4.2.7 on 2025-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommercialService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام خدمت")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت بازرگانی",
                "verbose_name_plural": "خدمات بازرگانی",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeasingService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام خدمت")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت لیزینگ",
                "verbose_name_plural": "خدمات لیزینگ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LegalService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام خدمت")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت حقوقی",
                "verbose_name_plural": "خدمات حقوقی",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LoanService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=200, verbose_name="نام بانک عامل"),
                ),
                ("plan_name", models.CharField(max_length=200, verbose_name="نام طرح")),
                (
                    "max_repayment_period",
                    models.PositiveIntegerField(
                        verbose_name="حداکثر مدت بازپرداخت (ماه)"
                    ),
                ),
                (
                    "max_plan_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="حداکثر مبلغ طرح"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت وام",
                "verbose_name_plural": "خدمات وام",
                "ordering": ["bank_name", "plan_name"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام خدمت")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت ثبت",
                "verbose_name_plural": "خدمات ثبت",
                "ordering": ["name"],
            },
        ),
    ]
