# Generated by Django 4.2.7 on 2025-11-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="آیکون"),
                ),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("chart", "نمودار"),
                            ("table", "جدول"),
                            ("stats", "آمار"),
                            ("info", "اطلاعات"),
                        ],
                        default="stats",
                        max_length=50,
                        verbose_name="نوع ویجت",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "ویجت داشبورد",
                "verbose_name_plural": "ویجت\u200cهای داشبورد",
                "ordering": ["order"],
            },
        ),
    ]
