# Generated by Django 4.2.7 on 2025-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_delete_usergroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="ادرس محل سکونت"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="شماره حساب بانکی"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="current_status",
            field=models.CharField(
                choices=[
                    ("active", "فعال"),
                    ("inactive", "غیرفعال"),
                    ("on_leave", "مرخصی"),
                    ("terminated", "پایان\u200cیافته"),
                ],
                default="active",
                max_length=20,
                verbose_name="وضعیت فعلی",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="document_file",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/", verbose_name="اپلود فایل"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="hire_date",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ استخدام"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="کد ملی"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="سمت"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["national_id"], name="accounts_cu_nationa_a453c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customuser",
            index=models.Index(
                fields=["current_status"], name="accounts_cu_current_2b3b5e_idx"
            ),
        ),
    ]
