# Generated by Django 4.2.7 on 2025-11-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_address_customuser_bank_account_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "ادمین"), ("user", "کاربر")],
                default="user",
                max_length=20,
                verbose_name="نقش",
            ),
        ),
    ]
