# Generated by Django 4.2.7 on 2025-11-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارمند",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تولید شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش کارمند",
                "verbose_name_plural": "گزارش\u200cهای کارمند",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["employee", "start_date", "end_date"],
                        name="reports_emp_employe_d7cc50_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_emp_created_807d0c_idx"
                    ),
                ],
            },
        ),
    ]
