# Generated by Django 4.2.7 on 2025-11-24 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="financial_reports_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تولید شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش مالی",
                "verbose_name_plural": "گزارش\u200cهای مالی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="reports_fin_start_d_801419_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_fin_created_98dba3_idx"
                    ),
                ],
            },
        ),
    ]
