# Generated by Django 4.2.7 on 2025-11-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persons", "0005_update_service_fields"),
        ("reports", "0002_financialreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "تمام دسته\u200cبندی\u200cها"),
                            ("commercial", "خدمات بازرگانی"),
                            ("registration", "خدمات ثبت"),
                            ("legal", "خدمات حقوقی"),
                            ("leasing", "خدمات لیزینگ"),
                            ("loan", "خدمات وام"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="دسته\u200cبندی خدمت",
                    ),
                ),
                (
                    "service_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="خدمت"
                    ),
                ),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[
                            ("all", "هر دو"),
                            ("sales", "فقط فاکتور فروش"),
                            ("purchase", "فقط فاکتور خرید"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="نوع فاکتور",
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[
                            ("all", "هر دو"),
                            ("cash", "نقدی"),
                            ("conditional", "شرایطی"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="نوع تسویه",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                (
                    "single_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ واحد"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ تولید گزارش"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customer_reports_generated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر ثبت\u200cکننده برای فیلتر",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_reports",
                        to="persons.person",
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_customer_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تولید شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش مشتری",
                "verbose_name_plural": "گزارش\u200cهای مشتری",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["customer", "generated_at"],
                        name="reports_cus_custome_be8f6e_idx",
                    ),
                    models.Index(
                        fields=["generated_at"], name="reports_cus_generat_fbb838_idx"
                    ),
                ],
            },
        ),
    ]
