# Generated by Django 5.2.8 on 2026-01-04 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_customerreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customerreport",
            name="generated_by",
        ),
        migrations.RemoveField(
            model_name="employeereport",
            name="generated_by",
        ),
        migrations.RemoveField(
            model_name="financialreport",
            name="generated_by",
        ),
        migrations.AddField(
            model_name="customerreport",
            name="filter_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_reports_filtered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر ثبت\u200cکننده برای فیلتر",
            ),
        ),
        migrations.AddField(
            model_name="employeereport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="customerreport",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
    ]
