# Generated by Django 4.2.7 on 2025-11-23 13:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=200, verbose_name="نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=12,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تماس باید یک شماره موبایل معتبر ایرانی باشد",
                                regex="^(\\+98|0)?9\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تماس اولی",
                    ),
                ),
                (
                    "phone_number_optional",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تماس باید یک شماره موبایل معتبر ایرانی باشد",
                                regex="^(\\+98|0)?9\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تماس دوم",
                    ),
                ),
                (
                    "national_id",
                    models.CharField(max_length=10, unique=True, verbose_name="کد ملی"),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "national_card_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="national_cards/",
                        verbose_name="تصویر کارت ملی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "شخص",
                "verbose_name_plural": "اشخاص",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="نام دسته\u200cبندی"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی خدمت",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای خدمت",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام خدمت")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="persons.servicecategory",
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
            ],
            options={
                "verbose_name": "خدمت",
                "verbose_name_plural": "خدمات",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="SalesInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="شماره پرونده"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="تاریخ")),
                (
                    "other_service_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="عنوان خدمت دیگر",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="قیمت فروش"
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[("cash", "نقدی"), ("conditional", "شرایطی")],
                        max_length=20,
                        verbose_name="نوع تسویه",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="persons.person",
                        verbose_name="خریدار",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persons.service",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persons.servicecategory",
                        verbose_name="دسته\u200cبندی خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور فروش",
                "verbose_name_plural": "فاکتورهای فروش",
                "ordering": ["-invoice_date", "-invoice_number"],
            },
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["national_id"], name="persons_per_nationa_098852_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="persons_per_first_n_764d18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="person",
            index=models.Index(
                fields=["phone_number"], name="persons_per_phone_n_23404b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="service",
            unique_together={("category", "name")},
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["invoice_number"], name="persons_sal_invoice_110d07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(
                fields=["invoice_date"], name="persons_sal_invoice_80c0df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="salesinvoice",
            index=models.Index(fields=["buyer"], name="persons_sal_buyer_i_928543_idx"),
        ),
    ]
