# Generated by Django 4.2.7 on 2025-11-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.PositiveIntegerField(
                        editable=False, unique=True, verbose_name="شماره پرونده"
                    ),
                ),
                ("invoice_date", models.DateField(verbose_name="تاریخ")),
                (
                    "other_service_title",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="عنوان خدمت دیگر",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="قیمت خرید"
                    ),
                ),
                (
                    "settlement_type",
                    models.CharField(
                        choices=[("cash", "نقدی"), ("conditional", "شرایطی")],
                        max_length=20,
                        verbose_name="نوع تسویه",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ به\u200cروز\u200cرسانی"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persons.service",
                        verbose_name="خدمت",
                    ),
                ),
                (
                    "service_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="persons.servicecategory",
                        verbose_name="دسته\u200cبندی خدمت",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_invoices",
                        to="persons.person",
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "فاکتور خرید",
                "verbose_name_plural": "فاکتورهای خرید",
                "ordering": ["-invoice_date", "-invoice_number"],
                "indexes": [
                    models.Index(
                        fields=["invoice_number"], name="persons_pur_invoice_37c3db_idx"
                    ),
                    models.Index(
                        fields=["invoice_date"], name="persons_pur_invoice_a7e8c4_idx"
                    ),
                    models.Index(
                        fields=["vendor"], name="persons_pur_vendor__203311_idx"
                    ),
                ],
            },
        ),
    ]
