# Generated by Django 4.2.7 on 2025-11-23 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persons", "0002_purchaseinvoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر ثبت کننده",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_invoices",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر ثبت کننده",
            ),
        ),
    ]
