# Generated by Django 4.2.7 on 2025-11-24 11:58

from django.db import migrations
from django.contrib.auth import get_user_model


def populate_created_by(apps, schema_editor):
    CustomUser = get_user_model()
    SalesInvoice = apps.get_model('persons', 'SalesInvoice')
    PurchaseInvoice = apps.get_model('persons', 'PurchaseInvoice')
    
    try:
        default_user = CustomUser.objects.first()
        if default_user:
            SalesInvoice.objects.filter(created_by__isnull=True).update(created_by=default_user)
            PurchaseInvoice.objects.filter(created_by__isnull=True).update(created_by=default_user)
    except Exception as e:
        pass


def reverse_populate_created_by(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0003_purchaseinvoice_created_by_salesinvoice_created_by"),
    ]

    operations = [
        migrations.RunPython(populate_created_by, reverse_populate_created_by),
    ]
