# Generated by Django 4.2.7 on 2025-11-27 11:00

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0005_update_service_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseinvoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="حداکثر حجم: 100 مگابایت",
                null=True,
                upload_to="purchase_invoices/",
                validators=[persons.models.validate_file_size_100mb],
                verbose_name="فایل پیوست",
            ),
        ),
        migrations.AddField(
            model_name="salesinvoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="حداکثر حجم: 100 مگابایت",
                null=True,
                upload_to="sales_invoices/",
                validators=[persons.models.validate_file_size_100mb],
                verbose_name="فایل پیوست",
            ),
        ),
    ]
