# Generated by Django 4.2.7 on 2025-11-27 11:04

from django.db import migrations, models
import persons.models


class Migration(migrations.Migration):
    dependencies = [
        ("persons", "0006_purchaseinvoice_attachment_salesinvoice_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseinvoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="حداکثر حجم: 100 مگابایت. فایل\u200cهای مجاز: ZIP, RAR, PDF, Excel, Word, تصاویر و فایل\u200cهای متنی",
                null=True,
                upload_to="purchase_invoices/",
                validators=[
                    persons.models.validate_file_size_100mb,
                    persons.models.validate_file_type,
                ],
                verbose_name="فایل پیوست",
            ),
        ),
        migrations.AlterField(
            model_name="salesinvoice",
            name="attachment",
            field=models.FileField(
                blank=True,
                help_text="حداکثر حجم: 100 مگابایت. فایل\u200cهای مجاز: ZIP, RAR, PDF, Excel, Word, تصاویر و فایل\u200cهای متنی",
                null=True,
                upload_to="sales_invoices/",
                validators=[
                    persons.models.validate_file_size_100mb,
                    persons.models.validate_file_type,
                ],
                verbose_name="فایل پیوست",
            ),
        ),
    ]
